# version: 3.9

services:
  web:
    image: my_site_info
    build:
      context: .
    ports:
      - '8001:8000'
    container_name: my_site_info
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: dan_dasakami.settings
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dan_dasakami
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 1908

  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: 1908
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'dan_dasakami'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dan_dasakami"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'


volumes:
  db-data: